(TeX-add-style-hook "mathforcs"
 (lambda ()
    (LaTeX-add-environments
     "theorem"
     "lemma"
     "proposition"
     "corollary"
     "definition"
     "example"
     "remark")
    (LaTeX-add-labels
     "sec:chapt-8-comm"
     "sec:complete-binary-tree"
     "sec:2-d-array"
     "sec:butterfly")
    (TeX-add-symbols
     "sig"
     "ra"
     "eps"
     "ah"
     "lam"
     "gam"
     "ol"
     "noi"
     "ben"
     "een"
     "beq"
     "enq"
     "hsone"
     "vsone"
     "hstwo"
     "So"
     "theset"
     "theequation")
    (TeX-run-style-hooks
     "amsthm"
     "amssymb"
     "amsmath"
     "latex2e"
     "art10"
     "article"
     "10pt")))

